### ISSUE TITLE
Setting state directly in componentDidMount

### ISSUE THREAD

**Issue by devserkan** [rwieruch/hackernews-client#1]
First of all, thank you for this great tutorial. I'm a new learner and it's a great opportunity to see tutorials like yours. 

To set searchKey as searchTerm we are setting the state in componentDidMount. But, if we do that first setState triggers the render. After that our ajax call triggers again. 

Why don't we set searchKey as DEFAULT_QUERY in the constructor state as we do for searchTerm?

Also our onChange state change triggers render every time, but I think this is out of context right know :) As a new learner I'm looking a neat solution for this.

**Comment by devserkan** [comment]
So, as I understand using onChange and triggering render is totally fine. No need to find a neat solution or even a solution. There is [uncontrolled component option](https://facebook.github.io/react/docs/uncontrolled-components.html) but this is needless for:

1. Rendering is so cheap.
2. VirtualDOM is looking for only the changes.
3. Single Source of Truth. Your values are always synced. 

For the subject of this issue, I think we can use both ways :) So, I'm closing.

**Comment by rwieruch** [comment]
Test

**Comment by rwieruch** [comment]
Test
