### ISSUE TITLE
Snapshot test fails if we don't use isomorphic-fetch

### ISSUE THREAD

**Issue by devserkan** [rwieruch/hackernews-client#2]
Error is:

```
TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror ......
```
Solution is install isomorphic-fetch:

```
yarn add isomorphic-fetch
```
and import it.

```
import fetch from "isomorphic-fetch";

```
in App.js.

**Comment by rwieruch** [comment]
Thank you very much, I will have a look at this! @devserkan can you answer me a couple of questions for this issue:

* Are you using create-react-app (like it is used in the book) or do you use any other boilerplate React project?
* Do the tests break already when you introduce them, or do they break in a chapter later on?

**Comment by devserkan** [comment]
You are welcome.

I've followed the book and used create-react-app. Test is failing at the very first step.
```
create-react-app --version
     1.3.0
grep react package.json
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-test-renderer": "^15.5.4"
    "react-scripts": "1.0.7"
``` 
For the sake of clarity, I cloned your repo and tried the test. Interestingly tests are passing but there is a warning (not error like mine) in the test console:

```
(node:27997) UnhandledPromiseRejectionWarning: Unhandled promise rejection 
(rejection id: 1): TypeError: Network request failed
(node:27997) [DEP0018] DeprecationWarning: Unhandled promise rejections are 
deprecated. In the future, promise rejections that are not handled will terminate the 
Node.js process with a non-zero exit code.

```

I can gladly provide any other info if you want.

**Comment by rwieruch** [comment]
Yes, that could be the issue. Do you use [nvm](https://github.com/creationix/nvm) to manage node versions? I can try it later as well. 🎉  I have to figure out this issue, because I heard it more often now 😄

**Comment by devserkan** [comment]
I wasn't using it but installed and tried some node versions. 
With: v7.10.0, v6.11.0 same error happens. Some older versions shoots another related one with this issue. Then note related with node maybe?

**Comment by devserkan** [comment]
Ok, I solved the issue without isomorphic-fetch. I don't know why but somehow test suit expect us to handle error for our promise, I think... So:

```
fetchSearchTopStories( searchTerm, page ) {
        fetch( `${ PATH_BASE }${ PATH_SEARCH }?${ PARAM_SEARCH }${ searchTerm
        }&${ PARAM_PAGE }${ page }&${ PARAM_HPP }${ DEFAULT_HPP } ` )
            .then( response => response.json() )
            .then( result => this.setSearchTopStories( result ) )
            .catch( err => err );    // ADD CATCH here.   
    }
```

**Comment by rwieruch** [comment]
That's great to know @devserkan I will take this into account for the next book edition. Thanks! See https://github.com/rwieruch/the-road-to-learn-react/issues/52

**Comment by devserkan** [comment]
Sorry for the late answer. Keep up the good work @rwieruch !
