### ISSUE TITLE
UnhandledPromiseRejectionWarning on Node 7.7.2 Bug

### ISSUE THREAD

**Issue by xjlim** [rwieruch/hackernews-client#3]
**Error**

`npm start`:
```
(node:36647) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: "listener" argument must be a function
(node:36647) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Environment**
1. `node -v`:
```
v7.7.2
```
2. `npm -v`:
```
4.1.2
```
3. `npm ls react-scripts`:
```
react-scripts@0.7.0
```
4. `OS`:
```
macOS Sierra version 10.12.5
```

**Comment by xjlim** [comment]
This has been fix by create-react-app release [v0.95](https://github.com/facebookincubator/create-react-app/releases/tag/v0.9.5).

Upgrading create-react-app fixes it.
`package.json`:
```
-    "react-scripts": "0.7.0",
+    "react-scripts": "0.9.5",
```

**Comment by rwieruch** [comment]
Thanks for reporting it and finding the fix that fast! I will take this into the next edition 👍

**Comment by rwieruch** [comment]
See https://github.com/rwieruch/the-road-to-learn-react/issues/51
